### ISSUE TITLE
MFXVideoVPP_Close + MFXVideoVPP_Init leaks resources

### ISSUE THREAD

**Issue by HermanMolinder** [Intel-Media-SDK/MediaSDK#105]
Setup:
Frames are generated live at 25 fps and composited with an OSD input. For each new frame (every 40 ms) the VPP block is closed and re-inited before composition.

By doing this the cpu usage is continuously increasing. If I replace close + init with MFXVideoVPP_Reset the cpu usage stays the same.

Additional info:
Video memory is used through vaapi.
Tested on Apollolake with embedded Linux and Intel Media SDK version 1.24

**Comment by alariono** [comment]
Hello,
Have you used sample_vpp for testsing? 
If yes, could you share cmd-line and par file for this case?

**Comment by HermanMolinder** [comment]
Hi,
No, I've used an application I've written myself which I cannot share the source code. If you need additional info I can provide it.

**Comment by artem-shaporenko** [comment]
@HermanMolinder can you check current OpenSource version - it can work on APL, there were some issues with memoryleaks in the past, but currently I believe should be fixed.

**Comment by HermanMolinder** [comment]
I'll give it a try and get back to you when tested.

**Comment by HermanMolinder** [comment]
@artem-shaporenko I've now tried with the OpenSource version of Intel Media SDK and unfortunately the problem still exists.

**Comment by maxha651** [comment]
Hi, Herman's colleague here.

The specific commit we are using currently is c7dd5fa4b813ace576c10bc2a004486421909a97.

**Comment by artem-shaporenko** [comment]
Ok, Let me raise this question to team.

**Comment by artem-shaporenko** [comment]
Ok, wanted to ask if reset working for you currently.

**Comment by HermanMolinder** [comment]
Reset doesn't leak any memory from what I've seen, but it suffers from the PiP issue. Preferably I would like to use the reset, as it takes less resources. The Init+Close was just a workaround for the PiP issue.

**Comment by dmitryermilov** [comment]
@HermanMolinder, could you collect valgrind report?
valgrind --tool=memcheck --leak-check=full --show-reachable=no --log-file=valgrind.txt ./your_app

**Comment by HermanMolinder** [comment]
@dmitryermilov @artem-shaporenko 

I first ran Valgrind with "--show.reachable=no" and couldn't find anything suspicious. Then I used "--show.reachable=yes" and found some suspicious mallocs, as shown in attached file.

In this test I had an empty parent session and did the composition in a child session. I let it ran for about 60 s and then properly closed the child session.

[valgrind.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/1899279/valgrind.txt)

**Comment by dmitryermilov** [comment]
Thanks. A few more questions and requests:
- What is the reason of calling Reset( or Close/Init as a workaround )?
- What is an approximate memory consumption growth rate e.g. per 100 frames?
- please collect libva traces:
$ mkdir /home/user/trace/
$ export LIBVA_TRACE=/home/user/trace/file
./your_app
logs will be in /home/user/trace/
- please collect msdk traces by /opt/intel/mediasdk/tools/tracer/

**Comment by dmitryermilov** [comment]
Thanks. I looked at libva traces. Unfortunately, there is nothing obvious which paints to a root cause of memory leak. So, looking toward to msdk traces.  I see two options for further investigation: 1) either you will create a simple reproducer (which can be shared with us) e.g. by modifying sample_vpp so that it behaves similar to your application or 2) I will do it. Of course I'd prefer the option №1.  Option №2 will take more time because I don't know how your application works and can only guess by looking at msdk traces. And there is always a chance that my reproducer will miss some part of logic of your code which triggers memory leak.

**Comment by HermanMolinder** [comment]
Okay,
Let me see if I can make a simple reproducer in the easiest way possible.

**Comment by HermanMolinder** [comment]
Here you have the source code for a reproducer. I didn't even have to use composition to reproduce, but just let it run through VPP. As you can see there's a define in the include file letting you choose to compile it with reset or with close+init.

I hope it's okay that you write your own main.c and makefile as I run it in a different environment.

[msdk_bug_reproducer.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/1903654/msdk_bug_reproducer.zip)

**Comment by dmitryermilov** [comment]
@HermanMolinder , I simplified the reproducer. Memory growth rate is the same as on your side on SKL with open source media-driver. But I don't have APL with the right setup at hands. Can you please try [driver_memleak_reproducer.tar.gz](https://github.com/Intel-Media-SDK/MediaSDK/files/1910559/driver_memleak_reproducer.tar.gz)  on APL with embedded MSDK API 1.24 ?

**Comment by HermanMolinder** [comment]
@dmitryermilov 
I have tried your simplified reproducer and were able to reproduce the memory leak with DEC, ENC and VPP on APL with open source MSDK.

You asked me to reproduce it on embedded MSDK API 1.24. However it's a bit tricky for me to switch back to 1.24 as it requires a completely new Yocto image/build. Is it enough that I've reproduced it in the open source version (from commint c7dd5fa) together with APL?

**Comment by dmitryermilov** [comment]
A fix for the memory growth issue:  [fix.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/1915197/fix.txt).

It will appear in opensource media-driver soon.

**Comment by HermanMolinder** [comment]
Great, thanks! Looking forward to it.

**Comment by dvrogozh** [comment]
@dmitryermilov : that's a fix in media driver. Did you create an issue in their repository to track when it will be addressed? And did you create a pull request?

**Comment by HermanMolinder** [comment]
@dmitryermilov 
Thank you and good job debugging.

**Comment by dmitryermilov** [comment]
You're welcome
