### ISSUE TITLE
Pass through mode for VIDEO->SYSTEM with MFX_FOURCC_A2RGB10 format

### ISSUE THREAD

**Issue by sunxinpeng** [Intel-Media-SDK/MediaSDK#1654]
When I support the feature "convert P010 to 10bit RGBA" in ffmpeg qsv, I find that if downloading the output surface from driver in MSDK, it will use MSDK VPP path(although I just want to get the surface without any vpp conversion). In this step, MFXVideoVPP_Init will fail because of the format of input context is MFX_FOURCC_A2RGB10(this format is supported for output only). So if MSDK can provide a method which can directly download the a2r10g10b10 surface without passing the vpp path?

**Comment by dmitryermilov** [comment]
It was fixed by https://github.com/Intel-Media-SDK/MediaSDK/pull/1664. 
Could you confirm?

**Comment by sunxinpeng** [comment]
> It was fixed by #1664.
> Could you confirm?
I have tested with the newest code. The path with IO pattern of "sys_to_sys"(sample_vpp) has passed. But hwdownload(video_to_sys) still failed because A2RGB10 is supported as output only which cause vpp init failed in msdk.

**Comment by dmitryermilov** [comment]
@AntonGrishin , can you please take a look?

**Comment by AntonGrishin** [comment]
Hi @sunxinpeng,
I tested with sample_vpp and  all iopattern`s works fine for me:
```
./sample_vpp -o outa2rgb10.yuv -i stream_352x288_24_p010.yuv  \
-sw 352 -sh 288 -iopattern d3d_to_sys -lib hw -sbitshift 1 -scc p010 \
-dcc a2rgb10 -n 10
```

**Comment by AntonGrishin** [comment]
Hi @sunxinpeng,
Can you please provide any updates?

**Comment by sunxinpeng** [comment]
Hi @AntonGrishin 
Sorry for the delay reply. Maybe you misunderstood my question. When I do vpp in ffmpeg qsv, the hwdownload stage need MSDK download the surface from the driver. I track the code and I find that it use MFXVideoVPP to do this task, which mean that the input format and the output format are both A2RGB10 for MFXVideoVPP_Init at the hwdownload stage. But MSDK limits the input format of 
MFXVideoVPP_Init to not be A2RGB10, which will cause failure when hwdownload. So if there is another API path to do this hwdownload of if MSDK can support download A2RGB10 surface using MFXVideoVPP?

**Comment by AntonGrishin** [comment]
Hi @sunxinpeng,

As I understand, ffmpeg called MFXVideoVPP_Init with wrong formats (sample_vpp works fine), so It think this is not MSDK problem, but ffmpeg.

Regarding to API, maybe @dmitryermilov can answer you question.

**Comment by fulinjie** [comment]
@AntonGrishin @dmitryermilov , is it possible to add identical logic like copy pass thru for  P010?
https://github.com/Intel-Media-SDK/MediaSDK/issues/1027
https://github.com/Intel-Media-SDK/MediaSDK/pull/1268

or allow A2RGB10 as an input for vpp if we only needs it for copy pass through?
or any other suggestions?

(Since X2RGB10 format is accepted in FFmpeg, we'd like to add full support for CSC in QSV now)

**Comment by dmitryermilov** [comment]
Hi @fulinjie ,

I can't restore full context. Could you remind me/explain more? For which exactly combination of input and output FOURCCs/memory types you'd like to have a passthru mode in VPP? AFAIR https://github.com/Intel-Media-SDK/MediaSDK/pull/1268/files introduced  passthru mode (simple copy) if input==output. But it seems you're requesting something different?

**Comment by fulinjie** [comment]
Fourcc:
In == Out (MFX_FOURCC_A2RGB10)

IOPattern: 
MFX_IOPATTERN_IN_VIDEO_MEMORY | MFX_IOPATTERN_OUT_SYSTEM_MEMORY

FFmpeg currently calls hwdownload to dump the data to system memory, which is a VPP procedure inside MSDK actually. 

The story is A2RGB10 is not allowed as an input fourcc for VPP: https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp#L1378
And A2RGB10 is not a supported input fourcc for the ddi caps:
https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/shared/src/mfx_vpp_vaapi.cpp#L472

So my quesion is:
FFmpeg now calls msdk to use VPP procedure to dump A2RGB10 data, is it possible to loose the restricts and allow A2RGB10 as an input while calling MFXVideoVPP_Init()?
since we only need it to be copied pass through.

**Comment by fulinjie** [comment]
For verifying, you may simply try this:
https://github.com/intel-media-ci/ffmpeg/pull/219

**Comment by dmitryermilov** [comment]
I got your point. Thanks for explanation. It's definitely technically feasible.  @FurongZhang , please enable it.

**Comment by AntonGrishin** [comment]
Hi @fulinjie,
I verified #2182 with sample_vpp.
Can you please try with ffmpeg?

**Comment by fulinjie** [comment]
> Hi @fulinjie,
> I verified #2182 with sample_vpp:
> 
> ```
> ./sample_vpp -i a2rgb10.yuv  -sw 352 -sh 288 -iopattern d3d_to_sys -lib hw -scc a2rgb10 -dcc a2rgb10 -n 10 -o cpthru.yuv
> ```
> 
> Can you please try with ffmpeg?

Hi @AntonGrishin, thanks for the quick response!
Had a quick check, however meet a synchronize error:

VPP PIPELINE:
MFX_EXTBUFF_VPP_RSHIFT_IN
RESIZE
CSC_A2RGB10
MFX_EXTBUFF_VPP_SCALING
VPP PIPELINE:
MFX_EXTBUFF_VPP_RSHIFT_IN
RESIZE
CSC_A2RGB10
MFX_EXTBUFF_VPP_SCALING
VPP PIPELINE:
MFX_EXTBUFF_VPP_RSHIFT_IN
RESIZE
CSC_A2RGB10
MFX_EXTBUFF_VPP_SCALING
VPP PIPELINE:
MFX_EXTBUFF_VPP_RSHIFT_IN
RESIZE
CSC_A2RGB10
MFX_EXTBUFF_VPP_SCALING
[Parsed_scale_qsv_0 @ 0x5627c37e6f40] w:64 h:64 -> w:64 h:64
VPP PIPELINE:
CSC_NV12
RESIZE
VPP PIPELINE:
CSC_NV12
RESIZE
VPP PIPELINE:
CSC_NV12
RESIZE
VPP PIPELINE:
CSC_NV12
RESIZE
[AVHWFramesContext @ 0x5627c37370c0] Error synchronizing the operation: -16
[hwdownload @ 0x5627c37e47c0] Failed to download frame: -1313558101.
Error while filtering: Unknown error occurred
Failed to inject frame into filter network: Unknown error occurred
Error while processing the decoded data for stream #0:0

I'll look into this later in FFmpeg.

**Comment by fulinjie** [comment]
Hi @AntonGrishin,

Confirmed that it seems to be something inside MSDK.
MFX_ERR_LOCK_MEMORY returned while calling mfxDefaultAllocatorVAAPI::SetFrameData() in Sync operation.

We'd better add support for A2RGB10 in SetFrameData() as well, otherwise it'll return MFX_ERR_LOCK_MEMORY by default.
https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/shared/src/libmfx_allocator_vaapi.cpp#L448

You may want to try or debug with ffmpeg just in case there is somewhere else needs the support too.
https://github.com/fulinjie/ffmpeg/tree/pr-qsv_csc_10bit

**Comment by AntonGrishin** [comment]
Hi @fulinjie,
As I understood, we have this support: 
https://github.com/Intel-Media-SDK/MediaSDK/blob/2ea69234a8ade11063d05dd2032c859ffee7b6be/_studio/shared/src/libmfx_allocator_vaapi.cpp#L518

**Comment by fulinjie** [comment]
> Hi @fulinjie,
> As I understood, we have this support:
> https://github.com/Intel-Media-SDK/MediaSDK/blob/2ea69234a8ade11063d05dd2032c859ffee7b6be/_studio/shared/src/libmfx_allocator_vaapi.cpp#L518

>> case VA_FOURCC_A2R10G10B10:

Let me be more clear:
FFmpeg uses VA_FOURCC_X2R10G10B10 instead of VA_FOURCC_A2R10G10B10, hence we'd meet this issue.

**Comment by fulinjie** [comment]
@AntonGrishin  Another thing is,

Why msdk needs to check each address of pDst->Data.R, pDst->Data.G, pDst->Data.B?
Note that A2RGB10 doesn't have a "byte adddress" for R or G plane, since they are packed 10 bits.

https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/shared/src/libmfx_core.cpp#L1497
case MFX_FOURCC_A2RGB10:
        {
            mfxU8* ptrSrc = std::min({pSrc->Data.R, pSrc->Data.G, pSrc->Data.B});
            mfxU8* ptrDst = std::min({pDst->Data.R, pDst->Data.G, pDst->Data.B});
...
        }


IMHO pDst->Data.A2RGB10 would be the exact field applications/users  want.

**Comment by fulinjie** [comment]
Verified that after these two concerns fixed(work around for now), the CSC to X2RGB10 works.

**Comment by fulinjie** [comment]
Hi @dmitryermilov , this issue is partially fixed by https://github.com/Intel-Media-SDK/MediaSDK/commit/a786fde3875b1470ab34c4cd6ce50c3d2448e993.

We still need @AntonGrishin's help for:
1.  Add  VA_FOURCC_X2R10G10B10 support in mfxStatus mfxDefaultAllocatorVAAPI::SetFrameData;
2.  Check whether it's possible to modify "ptrDst = std::min({pDst->Data.R, pDst->Data.G, pDst->Data.B});" inside MSDK.

**Comment by dmitryermilov** [comment]
Ohhh. Okay. You was confused my you last comment so merged the change. it was too early.

**Comment by fulinjie** [comment]
Hi @AntonGrishin, any further updates?

**Comment by AntonGrishin** [comment]
Hi @fulinjie, 
1. Basically, I`m not sure, that we can map VA_FOURCC_X2R10G10B10 to MFX_FOURCC_A2RGB10 because they are not fully the same (AFAIK, the first one is without alpha channel). Why FFmpeg use such mapping?
2. I think that we can modify this condition because R-G-B pointers are definitely the same

**Comment by fulinjie** [comment]
Hi @AntonGrishin ,

1. X2R10G10B10 could be taken as A2RGB10. This is required by FFmpeg community to avoid the false impression that we has alpha plane data supported in HW for now. The reason for adding this mapping is to address the concern from community,

2. Yes, please. And I'd prefer to use mfxA2RGB10 structure.

**Comment by AntonGrishin** [comment]
Hi @fulinjie,

Sorry, I was on vacation for the last two weeks. Can you please try #2268?
I checked with PR & cmd, and it`s worked for me.

**Comment by fulinjie** [comment]
Hi @AntonGrishin, commented in the pr, thx.

**Comment by daleksan** [comment]
@xhaihao could you cover this thread on behalf of @fulinjie ?

**Comment by FurongZhang** [comment]
I am following up this issue and double confirming with validation. After confirmation, I will close this issue if test results are good.

**Comment by daleksan** [comment]
Hi @FurongZhang  do you have any updates?
