### ISSUE TITLE
Windows: mfx_dispatch - buffer overrun possible in DriverStoreLoader::GetDriverStorePath

### ISSUE THREAD

**Issue by CarlG12** [Intel-Media-SDK/MediaSDK#2790]
In the method DriverStoreLoader::GetDriverStorePath of mfx_dispatch for Windows OS, a buffer overrun is possible with the following line:
` wcscat_s(path, MFX_MAX_DLL_PATH, L"\\");`

To fix the issue, MFX_MAX_DLL_PATH shall be replaced by the parameter dwPathSize

-----
Another issue is with the line:
`nError = RegQueryValueExW(hKey_sw, L"DriverStorePathForMediaSDK", 0, NULL, (LPBYTE)path, &pathSize);`

The following logic assumes that returned data type is a string(REG_SZ) and it is null terminated. However, do not perform these checks is dangerous because wsclen is used to get the len. If the string is not null terminated, buffer overrun is possible.

For more details, you can check the documentation of RegQueryValueExW: 
https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regqueryvalueexw

**Comment by onabiull** [comment]
@mvmaximov, could you please take a look at this issue?

**Comment by mvmaximov** [comment]
Should be fixed by https://github.com/Intel-Media-SDK/MediaSDK/pull/2801/

**Comment by CarlG12** [comment]
The issue is not fixed properly in method GetDriverStorePath

If you look this code:
```
nError = RegGetValueW(hKey_sw, NULL, L"DriverStorePathForMediaSDK", RRF_RT_ANY, NULL, (LPBYTE)path, &pathSize);

            RegCloseKey(hKey_sw);

            if (ERROR_SUCCESS == nError)
            {
                if (path[wcslen(path) - 1] != '/' && path[wcslen(path) - 1] != '\\')
                {
                    wcscat_s(path, dwPathSize / sizeof(path[0]), L"\\");
                }
                DISPATCHER_LOG_INFO(("DriverStore path is found\n"));
                return true;
            }
```

there is not guaranteed that path with be zero terminated after the call of RegGetValueW because the stored value might not be a null terminated string like REG_DWORD or REG_BINARY. The parameter RRF_RT_ANY indicates to accept any type.
